---

- name: Installing wfcli
  pip:
    <<: &pip_base
      state: latest
      executable: ~/bin/pip{{ server.python_version }}
    name: wfcli

- name: Securing website
  shell: >
    ~/bin/wfcli secure
    --webfaction-host={{ website.main.host }}
    --webfaction-user={{ webfaction_user }}
    --webfaction-password={{ webfaction_passwd }}
    {{ website.main.domain }}
  args:
    creates: ~/.acme.sh
